name: Deploy HTML para GitHub Pages

on:
  push:
    branches:
      - main  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar o repositório
        uses: actions/checkout@v3

      - name: Verificar a estrutura do HTML
        uses: cyb3r-jak3/html-validator-action@v1.3.0
        with:
          directory: ./ 

  deploy:
    needs: build  
    runs-on: ubuntu-latest
    steps:
      - name: Clonar o repositório
        uses: actions/checkout@v3
      
      - name: Implantar no GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages  
          folder: ./ 

